
name: Update Applications Metadata

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Run update script
      env:
        GH_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python source/scripts/maintenance/stats_updator.py

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add source/data/applications.json
        git commit -m "Auto-update GitHub metadata" || echo "No changes to commit"
        git push
